lapack: upgrade to latest 3.12.1
* adjust the list of .f files to cover also newly used .f90 files, causing:
  http://errors.yoctoproject.org/Errors/Details/840502/

ERROR: lapack-3.12.1-r0 do_package_qa: QA Issue: File /usr/lib/lapack/ptest/bin/xdmdeigtsts in package lapack-ptest contains reference to TMPDIR [buildpaths]
ERROR: lapack-3.12.1-r0 do_package_qa: QA Issue: File /usr/lib/lapack/ptest/bin/xdmdeigtstd in package lapack-ptest contains reference to TMPDIR [buildpaths]
ERROR: lapack-3.12.1-r0 do_package_qa: QA Issue: File /usr/lib/lapack/ptest/bin/xdmdeigtstz in package lapack-ptest contains reference to TMPDIR [buildpaths]
ERROR: lapack-3.12.1-r0 do_package_qa: QA Issue: File /usr/lib/lapack/ptest/bin/xdmdeigtstc in package lapack-ptest contains reference to TMPDIR [buildpaths]
ERROR: lapack-3.12.1-r0 do_package_qa: Fatal QA errors were found, failing task.

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>